services:
  app:
    env_file:
      - ./.env.${NODE_ENV}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: youcoinapp-backend
    ports:
      - '9000:3000'
    volumes:
      - .:/app
