export enum EnterStrategyName {
  MOMENTUM_INDICATORS = 'MOMENTUM_INDICATORS',
  VOLATILITY_INDICATORS = 'VOLATILITY_INDICATORS',
  SENTIMENT_INDICATORS = 'SENTIMENT_INDICATORS',
  RSI_REVERSAL = 'RSI_REVERSAL',
  PROFITABLE_SIMILARITY = 'PROFITABLE_SIMILARITY',
}
